export const START_POLL_BOOKINGS = 'START_POLL_BOOKINGS';
export const STOP_POLL_BOOKINGS = 'STOP_POLL_BOOKINGS';
export const FETCHED_BOOKINGS = 'FETCHED_BOOKINGS';
export const CANCEL_BOOKING = 'CANCEL_BOOKING';
export const CHECK_OUT_BOOKING = 'CHECK_OUT_BOOKING';
export const DELETE_BOOKING = 'DELETE_BOOKING';
